### ISSUE TITLE
CI is broken on autosynth

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-datacatalog#231] opened 2021-01-29 15:12 UTC
Looks like the system tests are failing on re-gen 😱

**Comment by sofisl** [comment] 2021-01-30 08:11
Thanks for submitting, Justin. I think the issue is [here](https://github.com/googleapis/nodejs-datacatalog/pull/230/files#r567215500). For some reason, those types are being deleted during regeneration. I've reached out to @alexander-fenster for his thoughts!

**Comment by bcoe** [comment] 2021-02-01 21:41
this is now fixed.

**Closed by bcoe** 2021-02-01 21:41 UTC
Labels: api: datacatalog, priority: p1, type: bug
